<def f='include/c++/4.9/exception' l='63' type='void std::exception::exception()'/>
